### ISSUE TITLE
create `linux-surface/linux` repo as fork of `torvalds/linux`

### ISSUE THREAD

**Issue by kasperk81** [linux-surface/kernel#131]
by creating this repo as fork, it will make it much easier to track how much we are diverging from upstream.
(similar to https://github.com/linux-surface/libwacom)

**Comment by qzed** [comment]
Creating it as a fork doesn't really give you any useful comparisons: By default we work on top of stable branches, so comparing directly to [torvalds/linux master](https://github.com/torvalds/linux) (which is what the default "this branch is ahead of ..." does) will give you a ton of unrelated differences (if it even works due to to the large amount of differences). So IMHO it's actively misleading rather than helpful and the main reason why this repo wasn't created as fork (see e.g. https://github.com/linux-surface/kernel/compare/master...v6.0-surface-devel for an example on how that would look like).

What you'll want to do is compare with the respective stable tags. I've just pushed a bunch of these (and will try to do so in the future too), so you can compare to those directly via e.g. https://github.com/linux-surface/kernel/compare/v6.0.1...v6.0-surface-devel.

**Comment by kasperk81** [comment]
thank you! and wow, these changes are upstreaming at much faster pace than i anticipated. (which is what i was looking for) 👍
