### ISSUE TITLE
Surface Book 1 dGPU

### ISSUE THREAD

**Issue by alexfreyre** [linux-surface/kernel#21]
First of all, i am completely pleased for your tremendous work on this kernel for surface devices, am a Cuban artist from fine arts who have a Surface Book 1, and I haven't more money to buy another laptop, I work on linux and i don't want for use my dGPU to have the two systems on my laptop... my work it's completely digital.

Please can you support the dGPU on Surface Book 1, is it too much difficult? Please i don't know how to do.... and i work with video editing, game engines... i don't want to use windows....

form linux itself i can't see the dGPU with lspci, i don't know if only with your kernel the dGPU could work or if i need a nvidia driver, which driver??? maybe a privative one? please help....

Moreover i have a doubt... you have two repositories, Linux-surface(jakeday fork) which it's that i am currently using, from the archlinux repo, but you have linux-surface-kernel repo here, which one i have to use??

i hope that you don't stop your wonderful work on this project,

Greetings

**Comment by qzed** [comment]
Sorry, this somehow slipped past me.

The dGPU can now be turned on via ACPI calls. More details can be found on https://github.com/linux-surface/linux-surface/issues/93.

Regarding repositories: This repository here is intended to maintain our modified kernel source and have a complete history of changes. The linux-surface repo (forked from jakeday/linux-surface) is intended for packaging the kernels, maintaining a set of patches grouped by features (rather than changes, as is done here), and general issue reporting.
