### ISSUE TITLE
HID: probe fails with "report is too long"

### ISSUE THREAD

**Issue by kitakar5525** [linux-surface/kernel#37]
Tracking the upstream bug: https://bugzilla.kernel.org/show_bug.cgi?id=206259
(Bug 206259 - HID ELAN9038 probe fails with "report is too long")

The commit 31d06cc8e7caec36bedeb4f90444920431462f61 (HID: Fix slab-out-of-bounds read in hid_field_extract)  breaks IPTS driver (the one that uses GuC submission on 4.19) and reportedly the touchscreen driver on Surface Go according to the buglink.

For the IPTS driver on 4.19, we have already added the following commits:
- 44c036ba808e1df71a4262999399a160bdd0d519 (HID: Do not abort on over-sized reports)
- 8acf3f6b0677f5ef95185366c7577815e614ae59 (ipts: prevent buffer-overflows by truncating HID reports)

Now, the upstream fixes have been landed on 5.6-rc4 as
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.6-rc4&id=84a4062632462c4320704fcdf8e99e89e94c0aba (HID: core: increase HID report buffer size to 8KiB)
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.6-rc4&id=5ebdffd25098898aff1249ae2f7dbfddd76d8f8f (HID: core: fix off-by-one memset in hid_report_raw_event())

So, let's see if those fixes will land on any stable/LTS releases, too.

### Environment

- Affected devices: IPTS driver (the one that uses GuC submission on 4.19), Touchscreen driver on Surface Go
- Kernel version: Any upstream stable/LTS kernels
- Distribution: not distribution specific

**Comment by kitakar5525** [comment]
Those upstream fixes have been added on all our using stable/LTS kernels (v5.5.8, v5.4.24 and v4.19.108).

**Comment by kitakar5525** [comment]
I tested on v4.19.108 and IPTS is now working without our fix (44c036ba808e1df71a4262999399a160bdd0d519).

@qzed
By the way, it works without 8acf3f6b0677f5ef95185366c7577815e614ae59. Should we still keep the commit? The commit seems to do nothing for me. Before v4.19.108, IPTS worked only with 44c036ba808e1df71a4262999399a160bdd0d519 and regardless of 8acf3f6b0677f5ef95185366c7577815e614ae59.

**Comment by qzed** [comment]
We should keep 8acf3f6. The [`hid_input_report`](https://github.com/linux-surface/kernel/blob/8acf3f6b0677f5ef95185366c7577815e614ae59/drivers/misc/ipts/ipts.h#L78) buffer has a fixed size of `HID_MAX_BUFFER_SIZE`, and in theory `raw_data_size_bytes` can be larger. While this should normally not happen (the oversized report should be caught already when reading the report descriptor and refuse probing the device, thus not allowing to get to that situation), we can't guarantee that the report will be declared in the descriptor, especially since the descriptor is given via firmware. So we need to keep this to ensure that the buffer isn't overrun and havoc is caused. We should probably also emit a warning there.

Thanks for the heads-up on the rest, I'll update the 4.19 branch.

**Comment by kitakar5525** [comment]
OK. Thanks! I made a PR for reverting only the commit 44c036b and keep 8acf3f6.

**Comment by kitakar5525** [comment]
The upstream bug "HID: probe fails with "report is too long"" has been fixed by upstream and we have dropped our fix. Closing.

**Comment by qzed** [comment]
Added 589ab3dbf4af3412daa40524024e58f8b548d263 to change the behavior on overflow. It now skips the report entirely and, as discussed, emits a warning.

**Comment by kitakar5525** [comment]
Thanks!
