### ISSUE TITLE
PRO 4: missing touch support with 5.5.8

### ISSUE THREAD

**Issue by Cyborgscode** [linux-surface/kernel#40]
Device: Surface Pro 4
Kernel: 5.5.8-1.surface.fc30.x86_64 build 6.3. 14:38
(which is actually newer than the Fedora one with 5.5.7 ) 

Description:

Firsttime installation of a surface kernel of your repo, so no refereces, if older kernels of this series are working. JakeDays kernelpatches did work and produced a working 5.1er kernel. 

Any ideas?

Working:
wifi
typcover

Mysterious:

it looks like it consumes less power ( none at all 100% battery for 5+ minutes ) .. or the battery check does not work at all. power-top says 4.7 W drain, which is a medium consumption. After a reboot it showed 95% dropping... so sort of works.

Missing Features:

Touchscreensupport 
Camera

Installed: 

kernel-surface-5.5.8-1.fc30.x86_64
surface-firmware-20191004-1.fc30.noarch
surface-secureboot-20200202-1.fc30.noarch
libwacom-surface-1.2-3.fc30.x86_64

Modules:

ipts 0x
mei 5x mei_hdcp,mei_me,ipts
i915  12x 
i2c_algo_bit 1x i915
drm_kms_helper 1x i915
drm 6x drm_kms_helper, i915
video 1x i915

**Comment by Cyborgscode** [comment]
Workaround: 
[root@surface]# rmmod ipts
[root@surface]# insmod /lib/modules/5.5.8-1.surface.fc30.x86_64/kernel/drivers/input/touchscreen/ipts/ipts.ko.xz singletouch=y 

singletouch seems to help this on SP4.

**Comment by StollD** [comment]
As per the notes for the release: https://github.com/linux-surface/linux-surface/issues/96#issuecomment-591720969

The 5.5+ based kernels include a new IPTS driver, since we cannot use the old one anymore due to the removal of GuC submission. The new driver currently supports **either** stylus input **or** singletouch. Stylus mode is enabled by default, you can enable singletouch by adding `ipts.singletouch` to the kernel command line, or setting the appropreate options in `/etc/modprobe.d`.

We still support 4.19 as an LTS release with support for the old IPTS driver, but I haven't gotten around to actually setting up LTS packages for fedora yet.

**Comment by qzed** [comment]
I think the main question has been answered, so I'm going to close this issue. I've opened a tracking issue for Fedora LTS builds: https://github.com/linux-surface/linux-surface/issues/120.
