### ISSUE TITLE
Driver for Surface ambient light sensor

### ISSUE THREAD

**Issue by qzed** [linux-surface/kernel#53]
It seems like the newer devices (SL3, SB3, maybe Pro7?) use a custom ambient light sensor. Implement support for this. CC @archseer.

**Comment by archseer** [comment]
I have an issue open here for SL3: https://github.com/linux-surface/linux-surface/issues/121

(I'm just dumping all issues in the primary repo since I find it easier to find)

SL3 sensor should probably just work with that driver, but it was impossible to bind it dynamically at runtime for some reason. Also wasn't able to recompile just iio because I'd get loading errors. I'd need to test with the kernel fully recompiled but I haven't bothered yet.

I think the SB3 sensor is different because I couldn't find the same i2c interfaces in the dsdt.

**Comment by qzed** [comment]
Okay, let's keep this one open as tracking issue and collect the info on the other one.

**Comment by pairwiserr** [comment]
Hello, @qzed and @archseer. How are you guys?

I am wondering if there's been any updates on this issue. Sensors are not available according to the feature matrix for **SL3 (I)**, but 
 according to [issue#121](https://github.com/linux-surface/linux-surface/issues/121), 

> All the registers seem to line up with apds9960, and I was able to turn on the sensor and read data from the same sequence as in that driver if I remember correctly. Should be as simple as adding the device to https://github.com/torvalds/linux/blob/fffb08b37df928475fef9c7f2aafddc2f6ebfaf4/drivers/iio/light/apds9960.c#L1111-L1121

it seems that it may be a simple fix? I am wondering if I can apply this fix on my end. Thanks, all!

**Comment by qzed** [comment]
No update from my side, can't really do much without having a device that has such a sensor.

**Comment by danielzgtg** [comment]
This seems to be implemented according to https://github.com/linux-surface/linux-surface/issues/96#issuecomment-766463825

**Comment by qzed** [comment]
Right, thanks for reminding me. The main part should be implemented in https://github.com/linux-surface/kernel/commit/23b180c407ed24eca2c2188401e264be9b123215 and working. There's still an open PR (https://github.com/linux-surface/kernel/pull/74) to introduce an additional `near_level` attribute, but I'm not sure if that's required.
